#################################################################
## Home Assistant Core
#################################################################

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - REDACTED.0/24
  customize: !include customize.yaml
default_config:
http:
  use_x_forREDACTEDed_for: true
  trusted_proxies:
    - REDACTED.33
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: false
#  login_attempts_threshold: 10
#logger:
#  default: warning
#  logs:
#    homeassistant.components.zha: debug

#################################################################
## Components
#################################################################

alarm_control_panel:
  - platform: manual
    name: Alarm
    code_arm_required: false
    arming_time: 30
    delay_time: 30
    trigger_time: 120
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 30
      delay_time: 30
      trigger_time: 120 
    armed_away:
      arming_time: 30
      delay_time: 15
      trigger_time: 120

route53:
  aws_access_key_id: !secret aws_access_key_id_route53
  aws_secret_access_key: !secret aws_secret_access_key_route53
  zone: !secret aws_zone_route53
  domain: !secret aws_domain_route53
  records:
    - home

weather:
  - platform: template
    name: "REDACTED, MO"
    unique_id: weather_REDACTED
    condition_template: "{{ states('sensor.weather_condition_REDACTED') }}"
    temperature_template: "{{ state_attr('weather.REDACTED_ecobee', 'temperature') }}"
    humidity_template: "{{ state_attr('weather.REDACTED_ecobee', 'humidity') }}"
    forecast_daily_template: "{{ state_attr('sensor.REDACTED_daily_forecast', 'forecast') }}"
    attribution_template: "{{ state_attr('weather.REDACTED_ecobee', 'attribution') }}"
    pressure_template: "{{ state_attr('weather.REDACTED_ecobee', 'pressure') }}"
    wind_speed_template: "{{ state_attr('weather.REDACTED_ecobee', 'wind_speed') }}"
    wind_bearing_template: "{{ state_attr('weather.REDACTED_ecobee', 'wind_bearing') }}"
    visibility_template: "{{ state_attr('weather.REDACTED_ecobee', 'visibility') }}"

#################################################################
## Notifications
#################################################################

notify:
  - platform: group
    name: REDACTED_devices
    services:
      - service: mobile_app_REDACTEDs_iphone
      - service: mobile_app_REDACTEDs_ipad
      - service: mobile_app_REDACTED_s_macbook_pro

  - platform: group
    name: USER2_devices
    services:
      - service: mobile_app_USER2s_iphone
      - service: mobile_app_USER2s_ipad

#################################################################
## Includes
#################################################################

automation manual: !include_dir_merge_list automation/
automation ui: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
homekit: !include homekit.yaml
switch: !include switch.yaml
emulated_hue: !include emulated_hue.yaml
template: !include template.yaml
command_line: !include command_line.yaml
python_script: