#################################################################
## Bedtime Automations
#################################################################

        ##########################################################
        ## Bedtime Locks
        ##########################################################

- alias: Bedtime - Locks
  id: 'bedtime_locks'

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: lock.lock
      entity_id:
       - lock.front_door
       - lock.back_door
       - lock.basement_door

        ##########################################################
        ## Bedtime Media
        ##########################################################

- alias: Bedtime - Media
  id: 'bedtime_media'

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 30

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: select.select_option
      data:
        entity_id: select.living_room_tv_activities
        option: "power_off"
    - service: select.select_option
      data:
        entity_id: select.USER1_s_office_tv_activities
        option: "power_off"
    - service: input_select.select_option
      data:
        entity_id: input_select.sonos
        option: "None"
    - service: media_player.media_stop
      entity_id:
        - media_player.sonos_surround_sound
        - media_player.sonos_living_room
        - media_player.sonos_dining_room
        - media_player.sonos_kitchen
        - media_player.sonos_bathroom
        - media_player.sonos_bedroom
        - media_player.sonos_bedroom_closet
        - media_player.sonos_USER1s_office
        - media_player.sonos_USER1s_office_move
        - media_player.sonos_USER2s_office
        - media_player.sonos_move
        - media_player.sonos_craft_room
        - media_player.sonos_fitness_room
        - media_player.sonos_backyard_patio
        - media_player.sonos_roam

        ##########################################################
        ## Bedtime Blinds
        ##########################################################

- alias: Bedtime - Blinds
  id: 'bedtime_blinds'

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: or
      conditions:
      - condition: state
        entity_id: cover.kitchen_blinds
        state: 'open'
      - condition: state
        entity_id: cover.bedroom_closet_blinds
        state: 'open'
      - condition: state
        entity_id: cover.stairs_blinds
        state: 'open'
      - condition: state
        entity_id: cover.USER2_s_office_blinds
        state: 'open'

  action:
    - service: cover.close_cover
      entity_id:
        - cover.USER2_s_office_blinds
    - service: cover.close_cover
      entity_id:
        - cover.stairs_blinds
    - service: cover.close_cover
      entity_id:
        - cover.bedroom_closet_blinds
    - service: cover.close_cover
      entity_id:
        - cover.kitchen_blinds

        ##########################################################
        ## Bedtime Helpers
        ##########################################################

- alias: Bedtime - Helpers
  id: 'bedtime_helpers'

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 3
        seconds: 0

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.interior_holiday
        - input_boolean.office_rainbow
        - input_boolean.livingroom_rainbow
        - input_boolean.bedroom_rainbow
        - input_boolean.front_porch_rainbow
        - input_boolean.pop_music
        - input_boolean.jazz_music
        - input_boolean.chill_music
        - input_boolean.electronic_music
        - input_boolean.classical_music
        - input_boolean.group_all_sonos

        ##########################################################
        ## Bedtime Fans
        ##########################################################

- alias: Bedtime - Fans
  id: 'bedtime_fans'

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 3
        seconds: 30

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: fan.turn_off
      entity_id:
        - fan.USER1s_office_fan
        - fan.living_room_east
        - fan.living_room_west

        ##########################################################
        ## Bedtime Switches
        ##########################################################

- alias: Bedtime - Switches
  id: 'bedtime_switches'

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 0

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.air_purifier
        - switch.lower_backyard_lighting
        - switch.backyard_patio_lighting
        - switch.fireplace
        - switch.fountain
        - switch.fountain_lights

        ##########################################################
        ## Bedtime Lights
        ##########################################################

- alias: Bedtime - Lights
  id: 'bedtime_lights'

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: light.interior_lights
      state: 'on'
    - condition: state
      entity_id: input_boolean.overnight_guest_mode
      state: 'off'

  action:
    - service: light.turn_off
      entity_id:
        - light.interior_lights
    - service: light.turn_off
      entity_id:
        - light.backyard_deck
    - service: light.turn_off
      entity_id:
        - light.garage_interior
    - service: light.turn_off
      entity_id:
        - light.backyard_patio
    - delay: '00:00:60'
    - service: light.turn_off
      entity_id:
        - light.interior_lights
    - service: light.turn_off
      entity_id:
        - light.backyard_deck
    - service: light.turn_off
      entity_id:
        - light.garage_interior
    - service: light.turn_off
      entity_id:
        - light.backyard_patio

        ##########################################################
        ## Bedtime Guest Mode
        ##########################################################

- alias: Bedtime - Guest Mode
  id: 'bedtime_guest_mode'

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.overnight_guest_mode
      state: 'on'

  action:
    - service: light.turn_off
      entity_id:
        - light.living_room_lights
    - service: light.turn_off
      entity_id:
        - light.dining_room_lights
    - service: light.turn_off
      entity_id:
        - light.bedroom_lights
    - service: light.turn_off
      entity_id:
        - light.USER2s_bedroom_closet
    - service: light.turn_off
      entity_id:
        - light.kitchen_lights
    - service: light.turn_off
      entity_id:
        - light.hallway_light
    - service: light.turn_off
      entity_id:
        - light.bathroom_lights
    - service: light.turn_off
      entity_id:
        - light.basement_lights
    - service: light.turn_off
      entity_id:
        - light.basement_stairs
    - service: light.turn_off
      entity_id:
        - light.work_bench_light
    - service: light.turn_off
      entity_id:
        - light.laundry_room_light
    - service: light.turn_off
      entity_id:
        - light.basement_stairs
    - service: light.turn_off
      entity_id:
        - light.craft_room_ceiling
    - service: light.turn_off
      entity_id:
        - light.fitness_room_ceiling
    - service: light.turn_off
      entity_id:
        - light.basement_lamp
    - service: light.turn_off
      entity_id:
        - light.USER1_office_lights
    - service: light.turn_off
      entity_id:
        - light.USER2_office_lights
    - service: light.turn_off
      entity_id:
        - light.backyard_deck
    - service: light.turn_off
      entity_id:
        - light.backyard_patio
    - service: light.turn_off
      entity_id:
        - light.garage_interior
    - service: climate.set_preset_mode
      data:
        entity_id: climate.main_floor
        preset_mode: 'smart3'
    - service: light.turn_off
      entity_id:
        - light.USER1s_office_desktop_clock
        - light.living_room_clock

        ##########################################################
        ## Bedtime Thermostat
        ##########################################################

- alias: Bedtime - Thermostat
  id: 'bedtime_thermostat'

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.overnight_guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.thermostat_away
      state: 'off'
    - condition: time
      after: '17:00:00'
      before: '23:00:00'

  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.main_floor
        preset_mode: 'Sleep'

        ##########################################################
        ## Bedtime Exterior Lights
        ##########################################################

- alias: Bedtime - Exterior Lights
  id: 'bedtime_exterior_lights'

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 30

  condition:
    - condition: time
      after: '00:00:00'
      before: '06:00:00'
    - condition: state
      entity_id: input_select.holiday
      state: 'None'

  action:
    - service: light.turn_off
      entity_id:
        - light.front_porch
    - service: light.turn_off
      entity_id:
        - light.back_door
    - service: light.turn_off
      entity_id:
        - light.garage_light
    - service: light.turn_off
      entity_id:
        - light.backyard_deck
    - service: light.turn_off
      entity_id:
        - light.garage_interior
    - service: light.turn_off
      entity_id:
        - light.backyard_patio
    - delay: '00:00:60'
    - service: light.turn_off
      entity_id:
        - light.front_porch
    - service: light.turn_off
      entity_id:
        - light.back_door
    - service: light.turn_off
      entity_id:
        - light.garage_light
    - service: light.turn_off
      entity_id:
        - light.backyard_deck
    - service: light.turn_off
      entity_id:
        - light.garage_interior
    - service: light.turn_off
      entity_id:
        - light.backyard_patio
    - service: switch.turn_off
      entity_id:
        - switch.lower_backyard_lighting
        - switch.backyard_patio_lighting
        - switch.fountain
        - switch.fountain_lights

        ##########################################################
        ## Bedtime Exterior Lights Holiday
        ##########################################################

- alias: Bedtime - Bedtime Exterior Lights Holiday
  id: 'bedtime_exterior_lights_holiday'

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 30

  condition:
    - condition: time
      after: '00:00:00'
      before: '07:30:00'
    - condition: not
      conditions:
        - condition: state
          entity_id: input_select.holiday
          state: 'None'

  action:
    - service: light.turn_off
      entity_id:
        - light.back_door
    - service: light.turn_off
      entity_id:
        - light.garage_light
    - service: light.turn_off
      entity_id:
        - light.backyard_patio
    - service: light.turn_off
      entity_id:
        - light.backyard_deck
    - service: light.turn_off
      entity_id:
        - light.garage_interior
    - service: switch.turn_off
      entity_id:
        - switch.lower_backyard_lighting
        - switch.backyard_patio_lighting
    - delay: '00:00:30'
    - service: light.turn_off
      entity_id:
        - light.back_door
    - service: light.turn_off
      entity_id:
        - light.garage_light
    - service: light.turn_off
      entity_id:
        - light.backyard_deck
    - service: light.turn_off
      entity_id:
        - light.garage_interior
    - service: light.turn_off
      entity_id:
        - light.backyard_patio

        ##########################################################
        ## Bedtime Garage Door
        ##########################################################

- alias: Bedtime - Garage Door
  id: 'bedtime_garage_door'

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 30

  condition:
    - condition: state
      entity_id: cover.garage_door
      state: 'open'
    - condition: state
      entity_id: input_boolean.garage_door_motor
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.garage_interior
      data:
       flash: long
    - delay: '00:00:15'
    - service: cover.close_cover
      entity_id: cover.garage_door

        ##########################################################
        ## Bedtime - USER1's Office Blinds
        ##########################################################

- alias: Bedtime USER1's Office Blinds
  id: 'bedtime_USER1_office_blinds'

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 30

  condition:
    - condition: state
      entity_id: binary_sensor.USER1s_office_window_right
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'

  action:
    - service: cover.close_cover
      entity_id:
        - cover.USER1_s_office_blinds

        ##########################################################
        ## Reset Bedtime Switch
        ##########################################################

- alias: Bedtime - Reset Switch
  id: 'bedtime_reset_switch'

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.bedtime
